version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 8080:80
        volumes:
            - "/var/www/html:ro"
        networks:
            - app-network
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.mdb
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "A.dmin123"
networks:
    app-network:

