FROM ubuntu:20.04
# USER root

# Keep upstart from complaining
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl

# Let the conatiner know that there is no tty
ENV DEBIAN_FRONTEND noninteractive

# Basic Requirements
RUN apt-get -y update
RUN cd / && apt-get install apt-utils -y
RUN apt-get -y upgrade
RUN apt-get -y install mysql-client nginx curl git unzip
RUN apt-get -y install php7.4 php7.4-fpm php7.4-gd php7.4-mysql

# nginx config
RUN sed -i -e"s/keepalive_timeout\s*65/keepalive_timeout 2/" /etc/nginx/nginx.conf
RUN sed -i -e"s/keepalive_timeout 2/keepalive_timeout 2;\n\tclient_max_body_size 100m/" /etc/nginx/nginx.conf
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

# nginx site conf
ADD nginx/nginx-site.conf /etc/nginx/sites-available/wordpress
RUN cd /etc/nginx && rm sites-enabled/default
RUN ln -s /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/


# Install Wordpress
ADD https://wordpress.org/latest.tar.gz /tmp/latest.tar.gz
RUN cd /tmp/ && tar xvf latest.tar.gz && rm latest.tar.gz
RUN cp /tmp/wordpress/wp-config-sample.php /tmp/wordpress/wp-config.php
RUN cp -a /tmp/wordpress/. /var/www/html
RUN rm -rf /tmp/wordpress
RUN chown -R www-data:www-data /var/www/html/

## Wordpress Initialization and Startup Script
ADD ./start_web.sh /start_web.sh
RUN chmod 755 /start_web.sh
#
## Private expose
EXPOSE 80
#
## Volume for wordpress install
VOLUME ["/var/www/html/"]
#
CMD ["/bin/bash", "/start_web.sh"]
