FROM mysql
ADD my.cnf /etc/mysql/
RUN sed -i -e"s/^bind-address\s*=\s*172.31.40.30/bind-address = 0.0.0.0/" /etc/mysql/my.cnf

# MySql Initialization and Startup Script
ADD ./start_db.sh /start_db.sh
RUN chmod 755 /start_db.sh

EXPOSE 3306

# volume for mysql database
VOLUME ["/var/lib/mysql"]

CMD ["/bin/bash", "/start_db.sh"]
